.TH DASH-CLI "1" "August 2017" "PURA-cli 0.12"
.SH NAME
PURA-cli \- a remote procedure call client for PURA Core. 
.SH SYNOPSIS
PURA-cli [options] <command> [params] \- Send command to PURA Core. 
.TP
PURA-cli [options] help \- Asks PURA Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the PURA-cli program. PURA-cli is an RPC client used to send commands to PURA Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBPURAd\fP, \fBPURA.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
